apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxconsole
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./FluxConsole/helm/fluxconsole
      sourceRef:
        kind: GitRepository
        name: flux-system
  values:
    image:
      repository: ghcr.io/ommkwn/fluxconsole
<<<<<<< HEAD
      tag: "1.0.0"
=======
      tag: "1.0.1"
>>>>>>> 7a633d3 (Added Helm chart and configuration files for Flux)
